
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;
export const API_ENDPOINTS = {
    HOMEPAGE_CATEGORY: "course/homepage-category-list/",
    LOGIN: "user/login/",
    FORGOT_PASSWORD: "user/forgot-password/",
    RESET_PASSWORD: "user/reset-password/",
    TAG: "course/homepage-tags/",
    COURSE_BY_ID: "course/homepage-tag-wise-courses",
    COURSE_LIST: "course/search/course/",
    COURSE_DETAIL: "course/course-detail/",
    ADD_TO_CART: "subscription/add-to-cart/",
    CHECK_COURSE_CART: "subscription/check-course-cart/",
    VIEW_CART: "subscription/view-cart/",
    HOMEPAGE_RECENTLY_ADDED: "course/homepage-recent-courses/",
    START_PAYMENT: "subscription/start-course-payment/",
    COMPLETE_PAYMENT: "subscription/complete-course-payment/",
    REMOVE_FROM_CART: "subscription/remove-to-cart/",
    WISHLIST: "user_study/get-user-wishlist/",
    TOGGLE_WISHLIST: "user_study/update-wishlist/",
    CATEGORY_FILTER: "course/search/filters-list/",
    COURSE_SEARCH_FILTER: "course/search/course/",
    UNREAD_NOTIFICATION: "user_study/get-user-notification/",
    MARK_AS_READ: "user_study/change-notification-status/",
    ALL_NOTIFICATION: "user_study/get-all-notification/",
    NOTIFICATION_SETTINGS_GET: "user_study/get-user-notification-setting/",
    NOTIFICATION_SETTINGS_UPDATE: "user_study/update-user-notification-setting/",
    CATEGORY_COURSES: "course/category/course/",

    GET_USER_PROFILE: "user/get-profile/",
    UPDATE_USER_PROFILE: "user/update-profile/",
    UPDATE_PROFILE_PICTURE: "user/update-profile-image/",
    MY_COURSES: "user_study/purchased-courses/",
    ADD_TO_MY_LIST: "user_study/mylist/create/",
    GET_DASHBOARD_CHAPTERS: "user_study/dashboard-chapters/",
    GET_DASHBOARD_CHAPTER_LECTURES: "user_study/chapter-lectures",
    GET_DASHBOARD_PDF_SIGNED_URL: "user_study/get-book-signed-url",
    WATCHED_VIDEO: "user_study/watch-video/",
    GET_COURSE_PROGRESS: "user_study/get-course-progress/",
    REGISTER: "user/register/",
    VERIFY_OTP: "user/verify-otp/",
    ALL_LECTURE_NOTES: "user_study/get-user-notes",
    CREATE_NOTE: "user_study/create-note/",
    UPDATE_NOTE: "user_study/update-note/",
    DELETE_NOTE: "user_study/delete-note/",
    ADD_REVIEW_RATING: "user_study/add-review-rating/",
    GET_REVIEW_RATING: "user_study/get-course-review",
    UPDATE_REVIEW_RATING: "user_study/update-review-rating/",
    DELETE_REVIEW_RATING: "user_study/delete-review-rating/",
    GET_ANNOUNCEMENTS: "course/get-courses-announcements-listing",
    ADD_COMMENT_ON_ANNOUNCEMENTS: "course/add-comment-in-course-announcements/",
    CREATE_REMINDER: "user_study/reminder/create/",
    UPDATE_REMINDER: "user_study/reminder/update/",
    DELETE_REMINDER: "user_study/reminder/delete/",
    GET_REMINDER: "user_study/reminder/get-reminders/",
}