
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;
export const API_ENDPOINTS = {
    HOMEPAGE_CATEGORY: "course/homepage-category-list/",
    LOGIN: "user/login/",
    FORGOT_PASSWORD: "user/forgot-password/",
    RESET_PASSWORD: "user/reset-password/",
    TAG: "course/homepage-tags/",
    COURSE_BY_ID: "course/homepage-tag-wise-courses",
    COURSE_LIST: "course/search/course/",
    COURSE_DETAIL: "course/course-detail/",
    ADD_TO_CART: "subscription/add-to-cart/",
    CHECK_COURSE_CART: "subscription/check-course-cart/",
    VIEW_CART: "subscription/view-cart/",
    HOMEPAGE_RECENTLY_ADDED: "course/homepage-recent-courses/",
    START_PAYMENT: "subscription/start-course-payment/",
    COMPLETE_PAYMENT: "subscription/complete-course-payment/",
    REMOVE_FROM_CART: "subscription/remove-to-cart/",
    WISHLIST: "user_study/get-user-wishlist/",
    TOGGLE_WISHLIST: "user_study/update-wishlist/",
    CATEGORY_FILTER: "course/search/filters-list/",
    COURSE_SEARCH_FILTER: "course/search/course/",
    UNREAD_NOTIFICATION: "user_study/get-user-notification/",
    MARK_AS_READ: "user_study/change-notification-status/",
    ALL_NOTIFICATION: "user_study/get-all-notification/",
    NOTIFICATION_SETTINGS_GET: "user_study/get-user-notification-setting/",
    NOTIFICATION_SETTINGS_UPDATE: "user_study/update-user-notification-setting/",
    GET_USER_PROFILE: "user/get-profile/",
    UPDATE_USER_PROFILE: "user/update-profile/",
    UPDATE_PROFILE_PICTURE: "user/update-profile-image/",
    MY_COURSES: "user_study/purchased-courses/",
    ADD_TO_MY_LIST: "user_study/mylist/create/",
    GET_DASHBOARD_CHAPTERS: "user_study/dashboard-chapters/",
    GET_DASHBOARD_CHAPTER_LECTURES: "user_study/chapter-lectures",
    GET_DASHBOARD_PDF_SIGNED_URL: "user_study/get-book-signed-url",
}